import { Geist, Geist_Mono } from "next/font/google";
import { Syne } from 'next/font/google';
// import { DM_Sans } from 'next/font/google';
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ['latin'],
})

const syne = Syne({
  variable: "--font-syne",
  subsets: ['latin'],
})
// const dmSans = DM_Sans({
//   variable: "--font-dmsans",
//   subsets: ['latin'],
// })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${syne.variable}  ${montserrat.variable} antialiased`}  
      >
          {/* ${dmSans.variable} */}
        
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
